version: '3'

services:
  # Configuración del servicio para la aplicación Node.js
  food-back:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: YaviFood-Backend
    ports:
      - "7085:5000"
    env_file:
      - ./src/.env
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
