version: '3'

services:
  yavifood:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yavifood_front
    ports:
      - "8085:5000"
    env_file:
      - ./src/.env
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
