version: '3'

services:
  # Configuración del servicio para la aplicación Node.js
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    ports:
      - "5000:5000"
    env_file:
      - ./src/.env
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
