FROM node:20 as build

WORKDIR /usr/src/app

COPY yaviFood/package*.json ./

RUN npm install

COPY yaviFood .

RUN npm run build

FROM nginx:alpine

COPY --from=build /usr/src/app/dist/frontend /usr/share/nginx/html

EXPOSE 80

CMD ["npm","start"]

# Nginx se inicia automáticamente, no es necesario un CMD