version: '3'

services:
  # Configuración del servicio para la aplicación Node.js
  yavidfood-front:
    build:
      context: .
      dockerfile: dockerfile
    container_name: yavifood
    ports:
      - "8075:4200"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
