import bcrypt from "bcryptjs";
export const sample_foods: any[] = [
  {
    id:'1',
    name: 'Caldo de Bolas',
    cookTime: '20-25',
    price: 10,
    favorite: false,
    origins: ['Ecuador'],
    stars: 4.5,
    imageUrl: 'sadas',
    tags: ['Sopas', 'Todo'],
  },
  {
    id:'2',
    name: 'Papas Fritas',
    price: 20,
    cookTime: '05-10',
    favorite: true,
    origins: ['Ecuador', 'Quito'],
    stars: 4.7,
    imageUrl: 'sad',
    tags: ['ComidaRapida', 'Todo'],
  },
  {
    id:'3',
    name: 'Menestra de Frejol',
    price: 50,
    cookTime: '10-15',
    favorite: false,
    origins: ['Manabi'],
    stars: 3.5,
    imageUrl: 'https://recetas123.net/wp-content/uploads/menestra-de-frejol.jpg',
    tags: ['Almuerzos', 'Todo'],
  },
  {
    id:'4',
    name: 'Tigrillo',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['Ecuador'],
    stars: 3.3,
    imageUrl: 'https://www.bonella.com.ec/-/media/Project/Upfield/Brands/Rama/Rama-EC/Assets/Recipes/sync-img/aee6aa7f-26b7-4327-b78b-051d06a86f51.jpg?rev=a5e10720d9dc445e89d96b438da6eb0a&w=900',
    tags: ['Desayunos', 'Todo'],
  },
  {
    id:'5',
    name: 'Gourmet',
    price: 110,
    cookTime: '40-50',
    favorite: false,
    origins: ['Ecuador'],
    stars: 5.0,
    imageUrl: 'https://aprende.com/wp-content/uploads/2022/06/platillo-gourmet.jpg',
    tags: ['Gourmet', 'Todo'],
  },
  {
    id:'6',
    name: 'Batido Fresa',
    price: 2,
    cookTime: '2 - 10',
    favorite: false,
    origins: ['Ecuador'],
    stars: 4.0,
    imageUrl: 'https://www.comedera.com/wp-content/uploads/2022/04/Batido-de-fresa-shutterstock_398479468.jpg',
    tags: ['Jugos', 'Todo'],
  },
]

export const sample_tags:any[] = [
  { name: 'All', count: 6 },
  { name: 'ComidaRapida', count: 4 },
  { name: 'Postres', count: 2 },
  { name: 'Almuerzos', count: 3 },
  { name: 'Desayunos', count: 2 },
  { name: 'Gourmet', count: 1 },
  { name: 'Jugos', count: 1 },
  { name: 'Sopas', count: 1 },
]

export const sample_users: any[] = [
  {
    name: "Angeles Quinatoa",
    email: "angeles@gmail.com",
    password: bcrypt.hashSync("12345", 10),
    address: "Toronto On",
    isAdmin: true,
  },
  {
    name: "Jinson Medina",
    email: "admin@admin.net",
    password: bcrypt.hashSync("12345", 10),
    address: "Catzuqui",
    isAdmin: true,
  },
  {
    name: "Alessandro Cisneros",
    email: "alessandro@gmail.com",
    password: bcrypt.hashSync("12345", 10),
    address: "Shanghai",
    isAdmin: false,
  },
  {
    name: "Mishel",
    email: "mishel@gmail.com",
    password: bcrypt.hashSync("12345", 10),
    address: "Quitumbe",
    isAdmin: false,
  },
];
